name: refresh spotify data

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SPOTIFY_TOKEN_CACHE: ${{ secrets.SPOTIFY_CACHED_TOKEN}}
on: 
  workflow_dispatch:
  push:
  # schedule:
    # - cron: 3 0,9,11,14,17,21 * * 1-5     
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Python Dependency Installation
      uses: py-actions/py-dependency-install@v3.0.0
    - name: update the data files
      run: python download_functions.py 
    - name: set cache as the secret 
      uses: gliech/create-github-secret-action@v1
      with:
        name: SPOTIFY_CACHED_TOKEN
        value: env.SPOTIFY_TOKEN_CACHE
        pa_token: ${{ secrets.GITHUB_TOKEN }}  
    - name: commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add ./data_out/*
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
