name: refresh spotify data

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *'     
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
#     - name: Automatic requirements.txt for Python Projects
#       uses: ryan-rozario/pipreqs-action@v2.0.0
    - name: Python Dependency Installation
      uses: py-actions/py-dependency-install@v3.0.0
    - name: update the data files
      run: python download_functions.py
    - name: commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add ./data_out/*
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
